
name: Build Native Helper

on:
  push:
    branches: [ main ]
    paths: [ 'native-helper/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'native-helper/**' ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: native-helper
        run: npm install
        
      - name: Build application
        working-directory: native-helper
        run: npm run build
        
      - name: Build Windows executable
        working-directory: native-helper
        run: npm run dist:win
        env:
          CSC_LINK: ${{ secrets.WINDOWS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-helper
          path: native-helper/releases/*.exe

  deploy:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Install Supabase CLI
        run: |
          curl -sSfL https://supabase.com/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Upload to Supabase Storage
        env:
          SUPABASE_URL: https://jafylkqbmvdptrqwwyed.supabase.co
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          # Upload Windows helper
          if [ -f windows-helper/*.exe ]; then
            curl -X POST "$SUPABASE_URL/storage/v1/object/native-helpers/InterviewAce-Helper-Windows.exe" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @windows-helper/*.exe
          fi
